### PR TITLE
Fixed several issues.

### PR DESCRIPTION
**Pull request by Liamb135**
- Fixed Llama Button not always appearing on https://www.deviantart.com/notifications
- Groups are now able to receive Llama Badges on all pages.
- The Edit button isn't considered to be a user on the About page.
- Can't send yourself a Llama on Notifications

### CODE REVIEW

**Comment by KishanBagaria** [comment]
can you run `yarn lint --fix` to fix the spacing? it'll also fix the diff

also main branch needs to be merged into this

**Comment by Liamb135** [comment]
Hi,

Sorry, could you explain how to do that? 🙂
________________________________

**Comment by KishanBagaria** [comment]
just did that for you. for more changes, i'd recommend deleting your fork on github and recreating it so that the newest changes are reflected.

**Comment by Liamb135** [comment]
Thanks!

I have Yarn set up on my PC for next time, so hopefully I can do it myself. Still very new to this, learning a lot!
________________________________

**Pull request merged**
